### ISSUE TITLE
Rendering readonly HUD & hierarchy

### ISSUE THREAD

**Issue by dresswithpockets** [dresswithpockets/PocketHud#1]
This issue is used to track and discuss HUD rendering - a major feature in PocketHud.

This is the first of the two primary feature sets in PocketHud. A user should be able to load an entire HUD from a folder, and view renders of each menu in that HUD. The renders should be as close to 1:1 with TF2's hud rendering as possible. This means inheriting oddities and bugs when known and feasible.

This roadmap is not immediately comprehensive, but should point to all issues relevant towards the stable release of a readonly render mode.

### Roadmap
- [ ] VGUI Backend
    - [ ] #3
    - [ ] #4
    - [ ] Drawing Targets (Image, TextImage)
    - [ ] #5
- [ ] VGUI Base Controls
    - [ ] Label
    - [ ] URLLabel
    - [ ] Button
    - [ ] ImageButton
    - [ ] ImagePanel
    - [ ] EditablePanel
    - [ ] and more...
- [ ] TF2 Extended Controls
    - [ ] CExLabel
    - [ ] CExButton
    - [ ] CExImageButton
    - [ ] CExRichText
    - [ ] CExplanationPopup
    - [ ] and more...
- [ ] Schemes
- [ ] Menus
    - [ ] Menu/view selection
    - [ ] Scene backgrounds
- [ ] Reactive layout
    - [ ] Aspect-ratio selection
- [ ] Simulation
